### ISSUE TITLE
[superl-url]超级网站URL采集软件第二版发布 - superl's blog

### ISSUE THREAD

**Issue by super-l** [super-l/superl.org#68]
http://www.superl.org/post-superlurl.html

**Comment by super-l** [comment]
可以使用github账户授权然后进行评论留言

**Comment by yylmylove** [comment]
大佬，安装了库文件也提示错误，Win10环境
[1;33;40mplease input keyword:hack
Search Number of pages:3
[1;37;40m==========================鐧惧害 绗?椤甸噰闆嗗紑濮?===============
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\superl-url-master\super-url.py", line 69, in <module>
    my_baidu.search(key, page_pn)
  File "C:\Users\Administrator\Desktop\superl-url-master\script\baidu.py", line 54, in search
    print ("\033[1;37;40m==========================鐧惧害 绗?s椤甸噰闆嗗紑濮?===============\n"%(page_num))
IOError: [Errno 0] Error

**Comment by super-l** [comment]
百度搜索关键词： “Win10环境 python 乱码 "之类的解决方法即可。最近准备优化一下程序，另外更新一个python3版本，python3在windows下就不会有中文乱码问题了

**Comment by cxrookie** [comment]
ConfigParser.NoSectionError: No section: 'global'
这是什么情况。。。。

**Comment by cxrookie** [comment]
Traceback (most recent call last):
  File "/root/桌面/superl-url-master/super-url.py", line 56, in <module>
    sleeptime = int(cfg.get("global", "sleeptime"))
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'global'

**Comment by super-l** [comment]
@cxrookie  目测应该是路径问题，看你的路径中有中文，可以尝试换一个英文目录，不要放在"桌面"等包含中文路径的地方。

**Comment by mcsetjz** [comment]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 16: illegal multibyte sequence ……

**Comment by Marchccc** [comment]
你好，我在filter_url.txt文件中追加了一些网址，但是搜索结果并没有把filter_url文件中我追加的网址过滤掉，不知道是什么问题，请问是我的使用方法不对吗？
